### PR TITLE
Fixed nextLink and made recursive to get all sub-folders and files

### PR DESCRIPTION
**Pull request by eduardomb08**
I also added logic to select the drive instead of always going with the default one.

### CODE REVIEW

**Review by 12Knocksinna — APPROVED** [review]
Thanks for the update

**Comment by eduardomb08** [comment]
Hi Tony,

No big deal, I'm just curious as of why I don't show under Contributors.. I don't contribute much to anything, so I may be missing something... (PS: I don't mind if you want to keep the list short with just main contributors).

Thanks and Best Regards,

Eduardo Monteiro de Barros
________________________________

**Comment by 12Knocksinna** [comment]
I didn't do anything to update or refine the contributor list. I leave that to GitHub to figure out. I'm sure you'll turn up eventually. It might be a background process that needs to fire up to update the list.

**Comment by eduardomb08** [comment]
Sounds good! Thanks!

Great stuff in the repo, btw!

Best Regards,

Eduardo Monteiro de Barros
________________________________

**Comment by eduardomb08** [comment]
FYI... I found out the reason it's not showing... I did the commit with my work e-mail and it must be the same e-mail in the GitHub account for it to show the contributor.

[cid:6b3643ad-9a82-4442-9806-bd16f24da2b3]

Best Regards,

Eduardo Monteiro de Barros
________________________________

**Comment by 12Knocksinna** [comment]
Well, go ahead and make another small change and commit using whatever address does the right thing and you'll get that status.

**Pull request merged**
